import Vehicules from "./vehicules"
export const VEHICULES:Vehicules[]=[{
    id:1,
    vehicule: "moto",
    marque: "Ducati",
    annee:2009,
    modele: "monster 696",
    img: "/DUCATI_MONSTER.jpg",
    km:36127,
    assureur:"macif",
    Energie	:"Essence",
    Cycle:	"4-temps",
    Type:"bicylindre",
    Disposition:	"en V (ou L)",
    Ouverture:	90,
    Cylindree:	696,
    Refroidissement:"par air",
    Distribution	:"desmodromique, 4 soup./cyl.",
    Alimentation:	"injection électronique",
    Démarrage	:"électrique",
    Puissance	:"80 ch (58,82 kW) à 9 000 tr/min",
    Couple	:"6,9 daN.m à 7 750 tr/min",
    Boîte	: "6, Boîte manuelle",
    Embrayage	:"hydraulique, multidisque à bain d'huile, assisté",
    Transmission	:"par chaîne"
},
{
    id:2,
    vehicule: "voiture",
    marque: "citroen",
    annee:2012,
    modele: "C3 picasso",
    img: "/C3P.png",
    km:186127,
    assureur:"macif",
    Energie	:"Essence",
    Cycle:	"4-temps",
    Type:"bicylindre",
    Disposition:	"en V (ou L)",
    Ouverture:	90,
    Cylindree:	696,
    Refroidissement:"par air",
    Distribution	:"desmodromique, 4 soup./cyl.",
    Alimentation:	"injection électronique",
    Démarrage	:"électrique",
    Puissance	:"80 ch (58,82 kW) à 9 000 tr/min",
    Couple	:"6,9 daN.m à 7 750 tr/min",
    Boîte	: "6, Boîte manuelle",
    Embrayage	:"hydraulique, multidisque à bain d'huile, assisté",
    Transmission	:"par chaîne"
},
{
    id:3,
    vehicule: "moto",
    marque: "Suzuki",
    annee:2005,
    modele: "chiron",
    img: "/sv650_2005.jpg",
    km:36127,
    assureur:"macif",
    Energie	:"Essence",
    Cycle:	"4-temps",
    Type:"bicylindre",
    Disposition:	"en V (ou L)",
    Ouverture:	90,
    Cylindree:	696,
    Refroidissement:"par air",
    Distribution	:"desmodromique, 4 soup./cyl.",
    Alimentation:	"injection électronique",
    Démarrage	:"électrique",
    Puissance	:"80 ch (58,82 kW) à 9 000 tr/min",
    Couple	:"6,9 daN.m à 7 750 tr/min",
    Boîte	: "6, Boîte manuelle",
    Embrayage	:"hydraulique, multidisque à bain d'huile, assisté",
    Transmission	:"par chaîne"
},
/* {
    id:4,
    vehicule: "voiture",
    marque: "Bugati",
    annee:2018,
    modele: "chiron",
    img: "/login.jpg",
    km:36127,
    assureur:"macif",
    Energie	:"Essence",
    Cycle:	"4-temps",
    Type:"bicylindre",
    Disposition:	"en V (ou L)",
    Ouverture:	90,
    Cylindree:	696,
    Refroidissement:"par air",
    Distribution	:"desmodromique, 4 soup./cyl.",
    Alimentation:	"injection électronique",
    Démarrage	:"électrique",
    Puissance	:"80 ch (58,82 kW) à 9 000 tr/min",
    Couple	:"6,9 daN.m à 7 750 tr/min",
    Boîte	: "6, Boîte manuelle",
    Embrayage	:"hydraulique, multidisque à bain d'huile, assisté",
    Transmission	:"par chaîne"
} */
]